version: "3.7"

services:
  helloworld:
    build:
      context: .
      dockerfile: Dockerfile
    image: "py-flask-sqlite:latest"
    container_name: "py-flask-sqlite"
    ports:
      - "8080:8080"
